/// <reference types="vite/client" />
/**
 * T030 — canonical MSW browser worker wiring.
 *
 * Purpose
 * -------
 * This module exposes the single MSW browser worker instance that the
 * small-dataset Asana fixture handlers (T029, `fixtures/asana/small-dataset/`)
 * are bound to at module-evaluation time. It exists so the local dev
 * server (`npm run dev`) and any browser-driven integration test (a
 * future Playwright `page.evaluate` hook, a Storybook-style harness)
 * boot the Asana API with a single import and a single `startDevWorker()`
 * call — never by manually constructing a `setupWorker` per call site.
 *
 * Why this module is dev-only
 * ---------------------------
 * Per `contracts/asana-client.md` § "Token handling" and Constitution
 * Principle IV, the production PWA must call the real Asana API with
 * a user-supplied PAT — shipping a fixture worker to production would
 * silently mock data the user believes is real (a privacy/correctness
 * violation). The dev-only guard in `startDevWorker()` rejects a call
 * from a production build so a future contributor who wires it into
 * `src/main.tsx` without a `import.meta.env.DEV` check fails fast
 * rather than shipping a fixture to a user.
 *
 * `mockServiceWorker.js`
 * ----------------------
 * The companion service-worker script that this module's worker
 * activates lives at `public/mockServiceWorker.js`. It is copied
 * verbatim from `node_modules/msw/lib/mockServiceWorker.js` (the
 * canonical MSW runtime file generated by `npx msw init public/ --save`)
 * during the local/CI install step and is committed to the repository
 * so the dev server serves it without a build-time codegen dependency.
 * Vite serves files under `public/` from the root URL path, so the
 * `serviceWorker.url` default of `/mockServiceWorker.js` matches the
 * file's served location with no further configuration.
 *
 * Boundary
 * --------
 * `src/mocks/**` is a top-level wiring module outside the
 * `src/{app,features,domain,data,shared}` boundary groups declared in
 * `eslint.config.js`. It imports the fixture handlers (a test/dev
 * artefact) and MSW's browser entry point only — never the real
 * `src/data/asana/client.ts`, never React. Keeping the worker free
 * of any code path that could touch a live Asana endpoint is what
 * lets the dev guard above be a single `import.meta.env.PROD` check
 * rather than a wider audit.
 *
 * Tests
 * -----
 * The browser worker is exercised end-to-end by the Phase 3+ contract
 * and integration tests that drive a real browser (`tests/e2e/*`,
 * Playwright) once the app shell ships (T031); no unit test is
 * registered here because MSW's worker setup requires a real Service
 * Worker registration, which jsdom does not provide.
 */

import { setupWorker } from "msw/browser";

import { asanaHandlers } from "../../fixtures/asana/small-dataset/handlers";

/**
 * The canonical MSW browser worker pre-loaded with the small-dataset
 * fixture handlers. Module-level so the handler list is captured
 * exactly once at evaluation time, mirroring `src/mocks/server.ts`.
 */
export const worker = setupWorker(...asanaHandlers);

/**
 * Start the MSW worker in development builds only.
 *
 * Throws in production builds (`import.meta.env.PROD === true`) so a
 * future contributor who wires this into `src/main.tsx` without a
 * `import.meta.env.DEV` guard fails fast rather than shipping a
 * fixture-backed mock to a user (see the module-level note on
 * "dev-only"). The thrown `Error` is descriptive enough to point a
 * code reviewer at the contract (`contracts/asana-client.md`) without
 * requiring them to read the dev guard source.
 *
 * The promise resolves with the activated `ServiceWorkerRegistration`
 * on success (or `undefined` if the worker was already active) and
 * rejects if the Service Worker registration fails (e.g. the
 * `mockServiceWorker.js` file is missing from `public/`). The
 * `{ onUnhandledRequest: "error" }` policy mirrors the canonical
 * Node server so a forgotten handler fails loudly in both runtimes.
 */
export async function startDevWorker(): Promise<
  ServiceWorkerRegistration | undefined
> {
  if (import.meta.env.PROD) {
    throw new Error(
      "MSW dev worker must not be started in a production build. " +
        'Per contracts/asana-client.md § "Token handling" and Constitution Principle IV, ' +
        "the production PWA must call the real Asana API with a user-supplied PAT. " +
        "Guard the call site with `import.meta.env.DEV`.",
    );
  }
  return worker.start({
    onUnhandledRequest: "error",
    serviceWorker: {
      url: "/mockServiceWorker.js",
    },
    quiet: false,
  });
}

/**
 * Stop the MSW worker and unregister its Service Worker. Call in any
 * browser-driven harness teardown that called `startDevWorker()` to
 * avoid leaking interceptors into a later test/page.
 */
export async function stopDevWorker(): Promise<void> {
  await worker.stop();
}
